spring.application.name=api-Gateway
server.port=8080

eureka.client.service-url.defaultZone=https://circuit-breaker-s6d7.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.routes[0].id=inventory-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/inventory/**

spring.cloud.gateway.server.webflux.routes[1].id=recommendation-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://RECOMMENDATION-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/recommendations/**

management.endpoints.web.exposure.include=health,info,gateway

spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=recommendationCB
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/fallback/recommendations

resilience4j.circuitbreaker.instances.recommendationCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.recommendationCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.recommendationCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.recommendationCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.recommendationCB.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.timelimiter.instances.recommendationCB.timeout-duration=3s

management.endpoints.web.exposure.include=health,info,gateway,circuitbreakers,circuitbreakerevents
management.health.circuitbreakers.enabled=true

spring.cloud.gateway.server.webflux.routes[1].filters[1].name=Bulkhead
resilience4j.bulkhead.instances.recommendationCB.max-concurrent-calls=5
resilience4j.bulkhead.instances.recommendationCB.max-wait-duration=0